### ISSUE TITLE
Working directory does not work with ignore option.

### ISSUE THREAD

**Issue by fcostarodrigo** [kaelzhang/node-glob-gitignore#6]
If I pass a part of the working directory and the ignore option I get a range error saying that paths need to be relative.

```js
const { join } = require('path');
const { glob } = require('glob-gitignore');
const ignore = require('ignore');

async function test() {
  console.log(await glob(process.cwd())); // [ CWD ]

  console.log(await glob('/bin')); // [ '/bin' ]

  try {
    await glob(process.cwd(), { ignore: ignore() })
  } catch (error) {
    // RangeError: path should be a `path.relative()`d string, but got CWD
  }


  try {
    await glob(join(process.cwd(), '..'), { ignore: ignore() })
  } catch (error) {
    // RangeError: path should be a `path.relative()`d string, but got CWD/..
  }

  try {
    await glob(join(process.cwd(), '*'), { ignore: ignore() })
  } catch (error) {
    // RangeError: path should be a `path.relative()`d string, but got CWD/randomFolder
  }

  try {
    await glob('..', { ignore: ignore() })
  } catch (error) {
    // RangeError: path should be a `path.relative()`d string, but got ".."
  }

  console.log(await glob(join('..', 'abc'), { ignore: ignore() })); // []

  console.log(await glob(process.cwd(), { ignore: ignore(), absolute: true })); // CWD
}

test();

```

```yml
  /glob-gitignore/1.0.14:
    dependencies:
      glob: 7.1.6
      ignore: 5.1.8
      lodash.difference: 4.5.0
      lodash.union: 4.6.0
      make-array: 1.0.5
      util.inherits: 1.0.3
```

```
node --version
v14.15.1
```
